// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artist is the predicate function for artist builders.
type Artist func(*sql.Selector)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// RecordCompany is the predicate function for recordcompany builders.
type RecordCompany func(*sql.Selector)
