// Code generated by ent, DO NOT EDIT.

package ent

import (
	"SoftwareGoDay2/ent/predicate"
	"SoftwareGoDay2/ent/recordcompany"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecordCompanyDelete is the builder for deleting a RecordCompany entity.
type RecordCompanyDelete struct {
	config
	hooks    []Hook
	mutation *RecordCompanyMutation
}

// Where appends a list predicates to the RecordCompanyDelete builder.
func (rcd *RecordCompanyDelete) Where(ps ...predicate.RecordCompany) *RecordCompanyDelete {
	rcd.mutation.Where(ps...)
	return rcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rcd *RecordCompanyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, rcd.sqlExec, rcd.mutation, rcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (rcd *RecordCompanyDelete) ExecX(ctx context.Context) int {
	n, err := rcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rcd *RecordCompanyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(recordcompany.Table, sqlgraph.NewFieldSpec(recordcompany.FieldID, field.TypeUUID))
	if ps := rcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	rcd.mutation.done = true
	return affected, err
}

// RecordCompanyDeleteOne is the builder for deleting a single RecordCompany entity.
type RecordCompanyDeleteOne struct {
	rcd *RecordCompanyDelete
}

// Where appends a list predicates to the RecordCompanyDelete builder.
func (rcdo *RecordCompanyDeleteOne) Where(ps ...predicate.RecordCompany) *RecordCompanyDeleteOne {
	rcdo.rcd.mutation.Where(ps...)
	return rcdo
}

// Exec executes the deletion query.
func (rcdo *RecordCompanyDeleteOne) Exec(ctx context.Context) error {
	n, err := rcdo.rcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recordcompany.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rcdo *RecordCompanyDeleteOne) ExecX(ctx context.Context) {
	if err := rcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
